name: infornet-dev
version: '3.8'
services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/dev/nginx/Dockerfile
        container_name: infornet-nginx-dev
        ports:
            - "80:80"
            - "5173:5173"
        volumes:
            - './vue:/var/www/html'
            - ./docker/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Mount Nginx config
        depends_on:
            - php-fpm
        networks:
            - infornet
    php-fpm:
        build:
            context: .
            dockerfile: ./docker/dev/php-fpm/Dockerfile
        volumes:
            - '.:/var/www/html'
        container_name: infornet-php-fpm-dev
        networks:
            - infornet

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        container_name: infornet-mysql-dev
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS}'
        
        volumes:
            - './docker/dev/mysql/data:/var/lib/mysql'
            - './docker/dev/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - infornet
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
                - mysql -u root -p${DB_PASSWORD}
            retries: 3
            timeout: 5s
networks:
    infornet:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
